# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'res/settings.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SettingsDialog(object):
    def setupUi(self, SettingsDialog):
        SettingsDialog.setObjectName("SettingsDialog")
        SettingsDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        SettingsDialog.resize(600, 424)
        self.gridLayout = QtWidgets.QGridLayout(SettingsDialog)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout.setObjectName("gridLayout")
        self.main_layout = QtWidgets.QVBoxLayout()
        self.main_layout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.main_layout.setObjectName("main_layout")
        self.header_layout = QtWidgets.QHBoxLayout()
        self.header_layout.setObjectName("header_layout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.header_layout.addItem(spacerItem)
        self.network_tool_button = QtWidgets.QToolButton(SettingsDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.network_tool_button.sizePolicy().hasHeightForWidth())
        self.network_tool_button.setSizePolicy(sizePolicy)
        self.network_tool_button.setMinimumSize(QtCore.QSize(75, 0))
        self.network_tool_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.network_tool_button.setCheckable(True)
        self.network_tool_button.setChecked(True)
        self.network_tool_button.setAutoExclusive(True)
        self.network_tool_button.setObjectName("network_tool_button")
        self.header_layout.addWidget(self.network_tool_button)
        self.paths_tool_button = QtWidgets.QToolButton(SettingsDialog)
        self.paths_tool_button.setMinimumSize(QtCore.QSize(75, 0))
        self.paths_tool_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.paths_tool_button.setCheckable(True)
        self.paths_tool_button.setChecked(False)
        self.paths_tool_button.setAutoExclusive(True)
        self.paths_tool_button.setObjectName("paths_tool_button")
        self.header_layout.addWidget(self.paths_tool_button)
        self.program_tool_button = QtWidgets.QToolButton(SettingsDialog)
        self.program_tool_button.setMinimumSize(QtCore.QSize(75, 0))
        self.program_tool_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.program_tool_button.setCheckable(True)
        self.program_tool_button.setAutoExclusive(True)
        self.program_tool_button.setObjectName("program_tool_button")
        self.header_layout.addWidget(self.program_tool_button)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.header_layout.addItem(spacerItem1)
        self.main_layout.addLayout(self.header_layout)
        self.stacked_widget = QtWidgets.QStackedWidget(SettingsDialog)
        self.stacked_widget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.stacked_widget.setObjectName("stacked_widget")
        self.network_page = QtWidgets.QWidget()
        self.network_page.setObjectName("network_page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.network_page)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.profile_group_box = QtWidgets.QGroupBox(self.network_page)
        self.profile_group_box.setObjectName("profile_group_box")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.profile_group_box)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.profile_view = QtWidgets.QListView(self.profile_group_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.profile_view.sizePolicy().hasHeightForWidth())
        self.profile_view.setSizePolicy(sizePolicy)
        self.profile_view.setObjectName("profile_view")
        self.verticalLayout_2.addWidget(self.profile_view)
        self.profile_buttons_layout = QtWidgets.QHBoxLayout()
        self.profile_buttons_layout.setObjectName("profile_buttons_layout")
        self.profile_add_button = QtWidgets.QToolButton(self.profile_group_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.profile_add_button.sizePolicy().hasHeightForWidth())
        self.profile_add_button.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme("add")
        self.profile_add_button.setIcon(icon)
        self.profile_add_button.setObjectName("profile_add_button")
        self.profile_buttons_layout.addWidget(self.profile_add_button)
        self.profile_edit_button = QtWidgets.QToolButton(self.profile_group_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.profile_edit_button.sizePolicy().hasHeightForWidth())
        self.profile_edit_button.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme("edit")
        self.profile_edit_button.setIcon(icon)
        self.profile_edit_button.setObjectName("profile_edit_button")
        self.profile_buttons_layout.addWidget(self.profile_edit_button)
        self.profile_remove_button = QtWidgets.QToolButton(self.profile_group_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.profile_remove_button.sizePolicy().hasHeightForWidth())
        self.profile_remove_button.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme("remove")
        self.profile_remove_button.setIcon(icon)
        self.profile_remove_button.setObjectName("profile_remove_button")
        self.profile_buttons_layout.addWidget(self.profile_remove_button)
        self.verticalLayout_2.addLayout(self.profile_buttons_layout)
        self.gridLayout_2.addWidget(self.profile_group_box, 0, 0, 1, 1)
        self.network_settings_grid = QtWidgets.QGridLayout()
        self.network_settings_grid.setObjectName("network_settings_grid")
        self.login_label = QtWidgets.QLabel(self.network_page)
        self.login_label.setObjectName("login_label")
        self.network_settings_grid.addWidget(self.login_label, 0, 0, 1, 1)
        self.profile_picn_path_label = QtWidgets.QLabel(self.network_page)
        self.profile_picn_path_label.setObjectName("profile_picn_path_label")
        self.network_settings_grid.addWidget(self.profile_picn_path_label, 7, 0, 1, 1)
        self.test_button = QtWidgets.QPushButton(self.network_page)
        self.test_button.setMaximumSize(QtCore.QSize(150, 16777215))
        self.test_button.setObjectName("test_button")
        self.network_settings_grid.addWidget(self.test_button, 8, 1, 1, 1)
        self.password_edit = QtWidgets.QLineEdit(self.network_page)
        self.password_edit.setMaximumSize(QtCore.QSize(150, 16777215))
        self.password_edit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_edit.setObjectName("password_edit")
        self.network_settings_grid.addWidget(self.password_edit, 1, 1, 1, 1)
        self.ftp_label = QtWidgets.QLabel(self.network_page)
        self.ftp_label.setObjectName("ftp_label")
        self.network_settings_grid.addWidget(self.ftp_label, 4, 0, 1, 1)
        self.http_port_layout = QtWidgets.QHBoxLayout()
        self.http_port_layout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.http_port_layout.setObjectName("http_port_layout")
        self.http_port_edit = QtWidgets.QLineEdit(self.network_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.http_port_edit.sizePolicy().hasHeightForWidth())
        self.http_port_edit.setSizePolicy(sizePolicy)
        self.http_port_edit.setMinimumSize(QtCore.QSize(50, 0))
        self.http_port_edit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.http_port_edit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.http_port_edit.setObjectName("http_port_edit")
        self.http_port_layout.addWidget(self.http_port_edit)
        self.http_ssl_check_box = QtWidgets.QCheckBox(self.network_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.http_ssl_check_box.sizePolicy().hasHeightForWidth())
        self.http_ssl_check_box.setSizePolicy(sizePolicy)
        self.http_ssl_check_box.setObjectName("http_ssl_check_box")
        self.http_port_layout.addWidget(self.http_ssl_check_box)
        self.network_settings_grid.addLayout(self.http_port_layout, 5, 1, 1, 1)
        self.telnet_label = QtWidgets.QLabel(self.network_page)
        self.telnet_label.setObjectName("telnet_label")
        self.network_settings_grid.addWidget(self.telnet_label, 6, 0, 1, 1)
        self.ftp_port_edit = QtWidgets.QLineEdit(self.network_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ftp_port_edit.sizePolicy().hasHeightForWidth())
        self.ftp_port_edit.setSizePolicy(sizePolicy)
        self.ftp_port_edit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.ftp_port_edit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ftp_port_edit.setObjectName("ftp_port_edit")
        self.network_settings_grid.addWidget(self.ftp_port_edit, 4, 1, 1, 1)
        self.http_label = QtWidgets.QLabel(self.network_page)
        self.http_label.setObjectName("http_label")
        self.network_settings_grid.addWidget(self.http_label, 5, 0, 1, 1)
        self.login_edit = QtWidgets.QLineEdit(self.network_page)
        self.login_edit.setMaximumSize(QtCore.QSize(150, 16777215))
        self.login_edit.setObjectName("login_edit")
        self.network_settings_grid.addWidget(self.login_edit, 0, 1, 1, 1)
        self.password_label = QtWidgets.QLabel(self.network_page)
        self.password_label.setObjectName("password_label")
        self.network_settings_grid.addWidget(self.password_label, 1, 0, 1, 1)
        self.host_label = QtWidgets.QLabel(self.network_page)
        self.host_label.setObjectName("host_label")
        self.network_settings_grid.addWidget(self.host_label, 2, 0, 1, 1)
        self.telnet_port_edit = QtWidgets.QLineEdit(self.network_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.telnet_port_edit.sizePolicy().hasHeightForWidth())
        self.telnet_port_edit.setSizePolicy(sizePolicy)
        self.telnet_port_edit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.telnet_port_edit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.telnet_port_edit.setObjectName("telnet_port_edit")
        self.network_settings_grid.addWidget(self.telnet_port_edit, 6, 1, 1, 1)
        self.host_edit = QtWidgets.QLineEdit(self.network_page)
        self.host_edit.setMaximumSize(QtCore.QSize(150, 16777215))
        self.host_edit.setObjectName("host_edit")
        self.network_settings_grid.addWidget(self.host_edit, 2, 1, 1, 1)
        self.port_label = QtWidgets.QLabel(self.network_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.port_label.sizePolicy().hasHeightForWidth())
        self.port_label.setSizePolicy(sizePolicy)
        self.port_label.setObjectName("port_label")
        self.network_settings_grid.addWidget(self.port_label, 3, 1, 1, 1)
        self.picon_path_box = QtWidgets.QComboBox(self.network_page)
        self.picon_path_box.setMaximumSize(QtCore.QSize(150, 16777215))
        self.picon_path_box.setObjectName("picon_path_box")
        self.network_settings_grid.addWidget(self.picon_path_box, 7, 1, 1, 1)
        self.gridLayout_2.addLayout(self.network_settings_grid, 0, 1, 1, 1)
        self.stacked_widget.addWidget(self.network_page)
        self.paths_page = QtWidgets.QWidget()
        self.paths_page.setObjectName("paths_page")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.paths_page)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.local_file_paths_box = QtWidgets.QGroupBox(self.paths_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.local_file_paths_box.sizePolicy().hasHeightForWidth())
        self.local_file_paths_box.setSizePolicy(sizePolicy)
        self.local_file_paths_box.setObjectName("local_file_paths_box")
        self.formLayout = QtWidgets.QFormLayout(self.local_file_paths_box)
        self.formLayout.setObjectName("formLayout")
        self.data_path_label = QtWidgets.QLabel(self.local_file_paths_box)
        self.data_path_label.setObjectName("data_path_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.data_path_label)
        self.backup_path_label = QtWidgets.QLabel(self.local_file_paths_box)
        self.backup_path_label.setObjectName("backup_path_label")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.backup_path_label)
        self.data_path_layout = QtWidgets.QHBoxLayout()
        self.data_path_layout.setSpacing(2)
        self.data_path_layout.setObjectName("data_path_layout")
        self.data_path_edit = QtWidgets.QLineEdit(self.local_file_paths_box)
        self.data_path_edit.setMinimumSize(QtCore.QSize(250, 0))
        self.data_path_edit.setText("")
        self.data_path_edit.setReadOnly(True)
        self.data_path_edit.setObjectName("data_path_edit")
        self.data_path_layout.addWidget(self.data_path_edit)
        self.browse_data_path_button = QtWidgets.QPushButton(self.local_file_paths_box)
        icon = QtGui.QIcon.fromTheme("folder-open")
        self.browse_data_path_button.setIcon(icon)
        self.browse_data_path_button.setObjectName("browse_data_path_button")
        self.data_path_layout.addWidget(self.browse_data_path_button)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.data_path_layout)
        self.backup_path_layout = QtWidgets.QHBoxLayout()
        self.backup_path_layout.setSpacing(2)
        self.backup_path_layout.setObjectName("backup_path_layout")
        self.backup_path_edit = QtWidgets.QLineEdit(self.local_file_paths_box)
        self.backup_path_edit.setMinimumSize(QtCore.QSize(250, 0))
        self.backup_path_edit.setReadOnly(True)
        self.backup_path_edit.setObjectName("backup_path_edit")
        self.backup_path_layout.addWidget(self.backup_path_edit)
        self.browse_backup_path_button = QtWidgets.QPushButton(self.local_file_paths_box)
        icon = QtGui.QIcon.fromTheme("folder-open")
        self.browse_backup_path_button.setIcon(icon)
        self.browse_backup_path_button.setObjectName("browse_backup_path_button")
        self.backup_path_layout.addWidget(self.browse_backup_path_button)
        self.formLayout.setLayout(6, QtWidgets.QFormLayout.FieldRole, self.backup_path_layout)
        self.picon_path_label = QtWidgets.QLabel(self.local_file_paths_box)
        self.picon_path_label.setObjectName("picon_path_label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.picon_path_label)
        self.picon_path_layout = QtWidgets.QHBoxLayout()
        self.picon_path_layout.setSpacing(2)
        self.picon_path_layout.setObjectName("picon_path_layout")
        self.picon_path_edit = QtWidgets.QLineEdit(self.local_file_paths_box)
        self.picon_path_edit.setMinimumSize(QtCore.QSize(250, 0))
        self.picon_path_edit.setReadOnly(True)
        self.picon_path_edit.setObjectName("picon_path_edit")
        self.picon_path_layout.addWidget(self.picon_path_edit)
        self.browse_picon_path_button = QtWidgets.QPushButton(self.local_file_paths_box)
        icon = QtGui.QIcon.fromTheme("folder-open")
        self.browse_picon_path_button.setIcon(icon)
        self.browse_picon_path_button.setObjectName("browse_picon_path_button")
        self.picon_path_layout.addWidget(self.browse_picon_path_button)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.picon_path_layout)
        self.gridLayout_3.addWidget(self.local_file_paths_box, 0, 1, 1, 1)
        self.stacked_widget.addWidget(self.paths_page)
        self.program_page = QtWidgets.QWidget()
        self.program_page.setObjectName("program_page")
        self.stacked_widget.addWidget(self.program_page)
        self.main_layout.addWidget(self.stacked_widget)
        self.gridLayout.addLayout(self.main_layout, 0, 0, 1, 1)
        self.action_button_box = QtWidgets.QDialogButtonBox(SettingsDialog)
        self.action_button_box.setOrientation(QtCore.Qt.Horizontal)
        self.action_button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok|QtWidgets.QDialogButtonBox.RestoreDefaults)
        self.action_button_box.setObjectName("action_button_box")
        self.gridLayout.addWidget(self.action_button_box, 1, 0, 1, 1)

        self.retranslateUi(SettingsDialog)
        self.stacked_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(SettingsDialog)

    def retranslateUi(self, SettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        SettingsDialog.setWindowTitle(_translate("SettingsDialog", "Settings"))
        self.network_tool_button.setText(_translate("SettingsDialog", "Network"))
        self.paths_tool_button.setText(_translate("SettingsDialog", "Paths"))
        self.program_tool_button.setText(_translate("SettingsDialog", "Program"))
        self.profile_group_box.setTitle(_translate("SettingsDialog", "Profile"))
        self.profile_add_button.setText(_translate("SettingsDialog", "Add"))
        self.profile_edit_button.setText(_translate("SettingsDialog", "Edit"))
        self.profile_remove_button.setText(_translate("SettingsDialog", "Remove"))
        self.login_label.setText(_translate("SettingsDialog", "Login:"))
        self.profile_picn_path_label.setText(_translate("SettingsDialog", "Picon path:"))
        self.test_button.setText(_translate("SettingsDialog", "Test"))
        self.ftp_label.setText(_translate("SettingsDialog", "FTP:"))
        self.http_ssl_check_box.setText(_translate("SettingsDialog", "SSL/TSL"))
        self.telnet_label.setText(_translate("SettingsDialog", "Telnet:"))
        self.http_label.setText(_translate("SettingsDialog", "HTTP:"))
        self.password_label.setText(_translate("SettingsDialog", "Password:"))
        self.host_label.setText(_translate("SettingsDialog", "Host:"))
        self.port_label.setText(_translate("SettingsDialog", "Port:"))
        self.local_file_paths_box.setTitle(_translate("SettingsDialog", "Local file paths"))
        self.data_path_label.setText(_translate("SettingsDialog", "Data path:"))
        self.backup_path_label.setText(_translate("SettingsDialog", "Backup path:"))
        self.browse_data_path_button.setText(_translate("SettingsDialog", "Choose..."))
        self.browse_backup_path_button.setText(_translate("SettingsDialog", "Choose..."))
        self.picon_path_label.setText(_translate("SettingsDialog", "Picons path:"))
        self.browse_picon_path_button.setText(_translate("SettingsDialog", "Choose..."))
