# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'res/main.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(997, 654)
        MainWindow.setMinimumSize(QtCore.QSize(720, 560))
        self.central_widget = QtWidgets.QWidget(MainWindow)
        self.central_widget.setObjectName("central_widget")
        self.gridLayout = QtWidgets.QGridLayout(self.central_widget)
        self.gridLayout.setObjectName("gridLayout")
        self.main_layout = QtWidgets.QVBoxLayout()
        self.main_layout.setSpacing(6)
        self.main_layout.setObjectName("main_layout")
        self.header_layout = QtWidgets.QHBoxLayout()
        self.header_layout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.header_layout.setContentsMargins(2, 5, 2, 5)
        self.header_layout.setSpacing(2)
        self.header_layout.setObjectName("header_layout")
        self.profile_combo_box = QtWidgets.QComboBox(self.central_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.profile_combo_box.sizePolicy().hasHeightForWidth())
        self.profile_combo_box.setSizePolicy(sizePolicy)
        self.profile_combo_box.setMinimumSize(QtCore.QSize(100, 0))
        self.profile_combo_box.setFrame(True)
        self.profile_combo_box.setObjectName("profile_combo_box")
        self.header_layout.addWidget(self.profile_combo_box)
        self.download_tool_button = QtWidgets.QToolButton(self.central_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.download_tool_button.sizePolicy().hasHeightForWidth())
        self.download_tool_button.setSizePolicy(sizePolicy)
        self.download_tool_button.setMinimumSize(QtCore.QSize(70, 0))
        self.download_tool_button.setArrowType(QtCore.Qt.NoArrow)
        self.download_tool_button.setObjectName("download_tool_button")
        self.header_layout.addWidget(self.download_tool_button)
        self.upload_tool_button = QtWidgets.QToolButton(self.central_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upload_tool_button.sizePolicy().hasHeightForWidth())
        self.upload_tool_button.setSizePolicy(sizePolicy)
        self.upload_tool_button.setMinimumSize(QtCore.QSize(70, 0))
        self.upload_tool_button.setArrowType(QtCore.Qt.NoArrow)
        self.upload_tool_button.setObjectName("upload_tool_button")
        self.header_layout.addWidget(self.upload_tool_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.header_layout.addItem(spacerItem)
        self.bouquet_tool_button = QtWidgets.QToolButton(self.central_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bouquet_tool_button.sizePolicy().hasHeightForWidth())
        self.bouquet_tool_button.setSizePolicy(sizePolicy)
        self.bouquet_tool_button.setMinimumSize(QtCore.QSize(75, 0))
        self.bouquet_tool_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bouquet_tool_button.setCheckable(True)
        self.bouquet_tool_button.setChecked(True)
        self.bouquet_tool_button.setAutoExclusive(True)
        self.bouquet_tool_button.setObjectName("bouquet_tool_button")
        self.header_layout.addWidget(self.bouquet_tool_button)
        self.satellite_tool_button = QtWidgets.QToolButton(self.central_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.satellite_tool_button.sizePolicy().hasHeightForWidth())
        self.satellite_tool_button.setSizePolicy(sizePolicy)
        self.satellite_tool_button.setMinimumSize(QtCore.QSize(75, 0))
        self.satellite_tool_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.satellite_tool_button.setCheckable(True)
        self.satellite_tool_button.setAutoExclusive(True)
        self.satellite_tool_button.setObjectName("satellite_tool_button")
        self.header_layout.addWidget(self.satellite_tool_button)
        self.picon_tool_button = QtWidgets.QToolButton(self.central_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.picon_tool_button.sizePolicy().hasHeightForWidth())
        self.picon_tool_button.setSizePolicy(sizePolicy)
        self.picon_tool_button.setMinimumSize(QtCore.QSize(75, 0))
        self.picon_tool_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.picon_tool_button.setCheckable(True)
        self.picon_tool_button.setAutoExclusive(True)
        self.picon_tool_button.setObjectName("picon_tool_button")
        self.header_layout.addWidget(self.picon_tool_button)
        self.tv_tool_button = QtWidgets.QToolButton(self.central_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tv_tool_button.sizePolicy().hasHeightForWidth())
        self.tv_tool_button.setSizePolicy(sizePolicy)
        self.tv_tool_button.setMinimumSize(QtCore.QSize(75, 0))
        self.tv_tool_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tv_tool_button.setCheckable(True)
        self.tv_tool_button.setAutoExclusive(True)
        self.tv_tool_button.setObjectName("tv_tool_button")
        self.header_layout.addWidget(self.tv_tool_button)
        self.epg_tool_button = QtWidgets.QToolButton(self.central_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.epg_tool_button.sizePolicy().hasHeightForWidth())
        self.epg_tool_button.setSizePolicy(sizePolicy)
        self.epg_tool_button.setMinimumSize(QtCore.QSize(75, 0))
        self.epg_tool_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.epg_tool_button.setCheckable(True)
        self.epg_tool_button.setAutoExclusive(True)
        self.epg_tool_button.setObjectName("epg_tool_button")
        self.header_layout.addWidget(self.epg_tool_button)
        self.timer_tool_button = QtWidgets.QToolButton(self.central_widget)
        self.timer_tool_button.setMinimumSize(QtCore.QSize(75, 0))
        self.timer_tool_button.setCheckable(True)
        self.timer_tool_button.setAutoExclusive(True)
        self.timer_tool_button.setObjectName("timer_tool_button")
        self.header_layout.addWidget(self.timer_tool_button)
        self.ftp_tool_button = QtWidgets.QToolButton(self.central_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ftp_tool_button.sizePolicy().hasHeightForWidth())
        self.ftp_tool_button.setSizePolicy(sizePolicy)
        self.ftp_tool_button.setMinimumSize(QtCore.QSize(75, 0))
        self.ftp_tool_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ftp_tool_button.setCheckable(True)
        self.ftp_tool_button.setAutoExclusive(True)
        self.ftp_tool_button.setObjectName("ftp_tool_button")
        self.header_layout.addWidget(self.ftp_tool_button)
        self.logo_tool_button = QtWidgets.QToolButton(self.central_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo_tool_button.sizePolicy().hasHeightForWidth())
        self.logo_tool_button.setSizePolicy(sizePolicy)
        self.logo_tool_button.setMinimumSize(QtCore.QSize(75, 0))
        self.logo_tool_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.logo_tool_button.setCheckable(True)
        self.logo_tool_button.setAutoExclusive(True)
        self.logo_tool_button.setObjectName("logo_tool_button")
        self.header_layout.addWidget(self.logo_tool_button)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.header_layout.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(170, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.header_layout.addItem(spacerItem2)
        self.control_tool_button = QtWidgets.QToolButton(self.central_widget)
        self.control_tool_button.setMinimumSize(QtCore.QSize(70, 0))
        self.control_tool_button.setCheckable(True)
        self.control_tool_button.setObjectName("control_tool_button")
        self.header_layout.addWidget(self.control_tool_button)
        self.main_layout.addLayout(self.header_layout)
        self.gridLayout.addLayout(self.main_layout, 0, 0, 1, 1)
        self.main_frame = QtWidgets.QFrame(self.central_widget)
        self.main_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.main_frame)
        self.gridLayout_4.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.main_splitter = QtWidgets.QSplitter(self.main_frame)
        self.main_splitter.setOrientation(QtCore.Qt.Horizontal)
        self.main_splitter.setObjectName("main_splitter")
        self.stacked_widget = QtWidgets.QStackedWidget(self.main_splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stacked_widget.sizePolicy().hasHeightForWidth())
        self.stacked_widget.setSizePolicy(sizePolicy)
        self.stacked_widget.setObjectName("stacked_widget")
        self.bouquet_page = QtWidgets.QWidget()
        self.bouquet_page.setObjectName("bouquet_page")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.bouquet_page)
        self.gridLayout_5.setContentsMargins(2, 0, 2, 2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.services_group_box = QtWidgets.QGroupBox(self.bouquet_page)
        self.services_group_box.setObjectName("services_group_box")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.services_group_box)
        self.verticalLayout.setContentsMargins(0, 6, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.search_filter_layout = QtWidgets.QHBoxLayout()
        self.search_filter_layout.setContentsMargins(6, -1, 6, -1)
        self.search_filter_layout.setObjectName("search_filter_layout")
        self.filter_free_button = QtWidgets.QToolButton(self.services_group_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filter_free_button.sizePolicy().hasHeightForWidth())
        self.filter_free_button.setSizePolicy(sizePolicy)
        self.filter_free_button.setCheckable(True)
        self.filter_free_button.setObjectName("filter_free_button")
        self.search_filter_layout.addWidget(self.filter_free_button)
        self.service_filter_edit = QtWidgets.QLineEdit(self.services_group_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.service_filter_edit.sizePolicy().hasHeightForWidth())
        self.service_filter_edit.setSizePolicy(sizePolicy)
        self.service_filter_edit.setInputMask("")
        self.service_filter_edit.setText("")
        self.service_filter_edit.setPlaceholderText("Filter..")
        self.service_filter_edit.setObjectName("service_filter_edit")
        self.search_filter_layout.addWidget(self.service_filter_edit)
        self.filter_type_combo_box = QtWidgets.QComboBox(self.services_group_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filter_type_combo_box.sizePolicy().hasHeightForWidth())
        self.filter_type_combo_box.setSizePolicy(sizePolicy)
        self.filter_type_combo_box.setObjectName("filter_type_combo_box")
        self.search_filter_layout.addWidget(self.filter_type_combo_box)
        self.filter_pos_combo_box = QtWidgets.QComboBox(self.services_group_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filter_pos_combo_box.sizePolicy().hasHeightForWidth())
        self.filter_pos_combo_box.setSizePolicy(sizePolicy)
        self.filter_pos_combo_box.setObjectName("filter_pos_combo_box")
        self.search_filter_layout.addWidget(self.filter_pos_combo_box)
        spacerItem3 = QtWidgets.QSpacerItem(13, 25, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.search_filter_layout.addItem(spacerItem3)
        self.service_search_edit = QtWidgets.QLineEdit(self.services_group_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.service_search_edit.sizePolicy().hasHeightForWidth())
        self.service_search_edit.setSizePolicy(sizePolicy)
        self.service_search_edit.setAutoFillBackground(False)
        self.service_search_edit.setInputMask("")
        self.service_search_edit.setText("")
        self.service_search_edit.setClearButtonEnabled(True)
        self.service_search_edit.setObjectName("service_search_edit")
        self.search_filter_layout.addWidget(self.service_search_edit)
        self.verticalLayout.addLayout(self.search_filter_layout)
        self.services_view = QtWidgets.QTableView(self.services_group_box)
        self.services_view.setObjectName("services_view")
        self.verticalLayout.addWidget(self.services_view)
        self.services_bottom_layout = QtWidgets.QHBoxLayout()
        self.services_bottom_layout.setContentsMargins(-1, -1, 6, -1)
        self.services_bottom_layout.setObjectName("services_bottom_layout")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.services_bottom_layout.addItem(spacerItem4)
        self.tv_label = QtWidgets.QLabel(self.services_group_box)
        self.tv_label.setObjectName("tv_label")
        self.services_bottom_layout.addWidget(self.tv_label)
        self.tv_count_label = QtWidgets.QLabel(self.services_group_box)
        self.tv_count_label.setObjectName("tv_count_label")
        self.services_bottom_layout.addWidget(self.tv_count_label)
        self.radio_label = QtWidgets.QLabel(self.services_group_box)
        self.radio_label.setObjectName("radio_label")
        self.services_bottom_layout.addWidget(self.radio_label)
        self.radio_count_label = QtWidgets.QLabel(self.services_group_box)
        self.radio_count_label.setObjectName("radio_count_label")
        self.services_bottom_layout.addWidget(self.radio_count_label)
        self.data_label = QtWidgets.QLabel(self.services_group_box)
        self.data_label.setObjectName("data_label")
        self.services_bottom_layout.addWidget(self.data_label)
        self.data_count_label = QtWidgets.QLabel(self.services_group_box)
        self.data_count_label.setObjectName("data_count_label")
        self.services_bottom_layout.addWidget(self.data_count_label)
        self.verticalLayout.addLayout(self.services_bottom_layout)
        self.gridLayout_5.addWidget(self.services_group_box, 1, 0, 1, 1)
        self.stacked_widget.addWidget(self.bouquet_page)
        self.satellite_page = QtWidgets.QWidget()
        self.satellite_page.setObjectName("satellite_page")
        self.stacked_widget.addWidget(self.satellite_page)
        self.picon_page = QtWidgets.QWidget()
        self.picon_page.setObjectName("picon_page")
        self.stacked_widget.addWidget(self.picon_page)
        self.tv_page = QtWidgets.QWidget()
        self.tv_page.setObjectName("tv_page")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tv_page)
        self.gridLayout_6.setContentsMargins(2, 0, 2, 2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.graphics_view = QtWidgets.QGraphicsView(self.tv_page)
        self.graphics_view.setObjectName("graphics_view")
        self.gridLayout_6.addWidget(self.graphics_view, 0, 0, 1, 1)
        self.stacked_widget.addWidget(self.tv_page)
        self.epg_page = QtWidgets.QWidget()
        self.epg_page.setObjectName("epg_page")
        self.stacked_widget.addWidget(self.epg_page)
        self.timer_page = QtWidgets.QWidget()
        self.timer_page.setObjectName("timer_page")
        self.stacked_widget.addWidget(self.timer_page)
        self.ftp_page = QtWidgets.QWidget()
        self.ftp_page.setObjectName("ftp_page")
        self.stacked_widget.addWidget(self.ftp_page)
        self.logo_page = QtWidgets.QWidget()
        self.logo_page.setObjectName("logo_page")
        self.stacked_widget.addWidget(self.logo_page)
        self.fav_splitter = QtWidgets.QSplitter(self.main_splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fav_splitter.sizePolicy().hasHeightForWidth())
        self.fav_splitter.setSizePolicy(sizePolicy)
        self.fav_splitter.setOrientation(QtCore.Qt.Vertical)
        self.fav_splitter.setOpaqueResize(True)
        self.fav_splitter.setHandleWidth(6)
        self.fav_splitter.setObjectName("fav_splitter")
        self.fav_group_box = QtWidgets.QGroupBox(self.fav_splitter)
        self.fav_group_box.setObjectName("fav_group_box")
        self.fav_layout = QtWidgets.QGridLayout(self.fav_group_box)
        self.fav_layout.setContentsMargins(0, 6, 2, 0)
        self.fav_layout.setVerticalSpacing(6)
        self.fav_layout.setObjectName("fav_layout")
        self.fav_view = QtWidgets.QTableView(self.fav_group_box)
        self.fav_view.setObjectName("fav_view")
        self.fav_layout.addWidget(self.fav_view, 3, 1, 1, 1)
        self.fav_h_layout = QtWidgets.QHBoxLayout()
        self.fav_h_layout.setContentsMargins(6, -1, 6, -1)
        self.fav_h_layout.setObjectName("fav_h_layout")
        self.fav_menu_button = QtWidgets.QToolButton(self.fav_group_box)
        self.fav_menu_button.setMinimumSize(QtCore.QSize(32, 0))
        self.fav_menu_button.setAutoRaise(False)
        self.fav_menu_button.setArrowType(QtCore.Qt.DownArrow)
        self.fav_menu_button.setObjectName("fav_menu_button")
        self.fav_h_layout.addWidget(self.fav_menu_button)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.fav_h_layout.addItem(spacerItem5)
        self.bq_service_search_edit = QtWidgets.QLineEdit(self.fav_group_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bq_service_search_edit.sizePolicy().hasHeightForWidth())
        self.bq_service_search_edit.setSizePolicy(sizePolicy)
        self.bq_service_search_edit.setInputMask("")
        self.bq_service_search_edit.setText("")
        self.bq_service_search_edit.setObjectName("bq_service_search_edit")
        self.fav_h_layout.addWidget(self.bq_service_search_edit)
        self.fav_layout.addLayout(self.fav_h_layout, 0, 1, 1, 1)
        self.bouquets_group_box = QtWidgets.QGroupBox(self.fav_splitter)
        self.bouquets_group_box.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.bouquets_group_box.setObjectName("bouquets_group_box")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.bouquets_group_box)
        self.gridLayout_3.setContentsMargins(0, 6, 2, 2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.bouquets_view = QtWidgets.QTreeView(self.bouquets_group_box)
        self.bouquets_view.setObjectName("bouquets_view")
        self.gridLayout_3.addWidget(self.bouquets_view, 3, 0, 1, 1)
        self.bq_h_layout = QtWidgets.QHBoxLayout()
        self.bq_h_layout.setContentsMargins(6, -1, 6, -1)
        self.bq_h_layout.setObjectName("bq_h_layout")
        self.add_bouquet_button = QtWidgets.QToolButton(self.bouquets_group_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_bouquet_button.sizePolicy().hasHeightForWidth())
        self.add_bouquet_button.setSizePolicy(sizePolicy)
        self.add_bouquet_button.setMinimumSize(QtCore.QSize(32, 0))
        icon = QtGui.QIcon.fromTheme("add")
        self.add_bouquet_button.setIcon(icon)
        self.add_bouquet_button.setAutoRaise(False)
        self.add_bouquet_button.setObjectName("add_bouquet_button")
        self.bq_h_layout.addWidget(self.add_bouquet_button)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.bq_h_layout.addItem(spacerItem6)
        self.gridLayout_3.addLayout(self.bq_h_layout, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.main_splitter, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.main_frame, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.central_widget)
        self.menu_bar = QtWidgets.QMenuBar(MainWindow)
        self.menu_bar.setGeometry(QtCore.QRect(0, 0, 997, 22))
        self.menu_bar.setObjectName("menu_bar")
        self.file_menu = QtWidgets.QMenu(self.menu_bar)
        self.file_menu.setObjectName("file_menu")
        self.help_menu = QtWidgets.QMenu(self.menu_bar)
        self.help_menu.setObjectName("help_menu")
        self.settings_menu = QtWidgets.QMenu(self.menu_bar)
        self.settings_menu.setObjectName("settings_menu")
        self.language_menu = QtWidgets.QMenu(self.settings_menu)
        self.language_menu.setObjectName("language_menu")
        self.view_menu = QtWidgets.QMenu(self.menu_bar)
        self.view_menu.setObjectName("view_menu")
        self.menuTools = QtWidgets.QMenu(self.view_menu)
        self.menuTools.setObjectName("menuTools")
        MainWindow.setMenuBar(self.menu_bar)
        self.status_bar = QtWidgets.QStatusBar(MainWindow)
        self.status_bar.setObjectName("status_bar")
        MainWindow.setStatusBar(self.status_bar)
        self.open_action = QtWidgets.QAction(MainWindow)
        self.open_action.setObjectName("open_action")
        self.exit_action = QtWidgets.QAction(MainWindow)
        self.exit_action.setObjectName("exit_action")
        self.settings_action = QtWidgets.QAction(MainWindow)
        self.settings_action.setObjectName("settings_action")
        self.menu_action_search = QtWidgets.QAction(MainWindow)
        self.menu_action_search.setCheckable(True)
        self.menu_action_search.setChecked(True)
        self.menu_action_search.setObjectName("menu_action_search")
        self.menu_action_filter = QtWidgets.QAction(MainWindow)
        self.menu_action_filter.setCheckable(True)
        self.menu_action_filter.setChecked(True)
        self.menu_action_filter.setObjectName("menu_action_filter")
        self.import_action = QtWidgets.QAction(MainWindow)
        self.import_action.setObjectName("import_action")
        self.extract_action = QtWidgets.QAction(MainWindow)
        self.extract_action.setObjectName("extract_action")
        self.about_action = QtWidgets.QAction(MainWindow)
        self.about_action.setObjectName("about_action")
        self.english_lang_action = QtWidgets.QAction(MainWindow)
        self.english_lang_action.setCheckable(True)
        self.english_lang_action.setChecked(True)
        self.english_lang_action.setObjectName("english_lang_action")
        self.bouquets_action = QtWidgets.QAction(MainWindow)
        self.bouquets_action.setCheckable(True)
        self.bouquets_action.setChecked(True)
        self.bouquets_action.setObjectName("bouquets_action")
        self.satellites_action = QtWidgets.QAction(MainWindow)
        self.satellites_action.setCheckable(True)
        self.satellites_action.setEnabled(False)
        self.satellites_action.setObjectName("satellites_action")
        self.picons_action = QtWidgets.QAction(MainWindow)
        self.picons_action.setCheckable(True)
        self.picons_action.setEnabled(False)
        self.picons_action.setObjectName("picons_action")
        self.tv_action = QtWidgets.QAction(MainWindow)
        self.tv_action.setCheckable(True)
        self.tv_action.setChecked(True)
        self.tv_action.setObjectName("tv_action")
        self.epg_action = QtWidgets.QAction(MainWindow)
        self.epg_action.setCheckable(True)
        self.epg_action.setChecked(True)
        self.epg_action.setObjectName("epg_action")
        self.timer_action = QtWidgets.QAction(MainWindow)
        self.timer_action.setCheckable(True)
        self.timer_action.setEnabled(False)
        self.timer_action.setObjectName("timer_action")
        self.ftp_action = QtWidgets.QAction(MainWindow)
        self.ftp_action.setCheckable(True)
        self.ftp_action.setEnabled(False)
        self.ftp_action.setObjectName("ftp_action")
        self.logo_action = QtWidgets.QAction(MainWindow)
        self.logo_action.setCheckable(True)
        self.logo_action.setEnabled(False)
        self.logo_action.setObjectName("logo_action")
        self.file_menu.addAction(self.import_action)
        self.file_menu.addAction(self.open_action)
        self.file_menu.addAction(self.extract_action)
        self.file_menu.addSeparator()
        self.file_menu.addAction(self.exit_action)
        self.help_menu.addAction(self.about_action)
        self.language_menu.addAction(self.english_lang_action)
        self.settings_menu.addAction(self.settings_action)
        self.settings_menu.addSeparator()
        self.settings_menu.addAction(self.language_menu.menuAction())
        self.menuTools.addAction(self.bouquets_action)
        self.menuTools.addAction(self.satellites_action)
        self.menuTools.addAction(self.picons_action)
        self.menuTools.addAction(self.tv_action)
        self.menuTools.addAction(self.epg_action)
        self.menuTools.addAction(self.timer_action)
        self.menuTools.addAction(self.ftp_action)
        self.menuTools.addAction(self.logo_action)
        self.view_menu.addAction(self.menuTools.menuAction())
        self.menu_bar.addAction(self.file_menu.menuAction())
        self.menu_bar.addAction(self.view_menu.menuAction())
        self.menu_bar.addAction(self.settings_menu.menuAction())
        self.menu_bar.addAction(self.help_menu.menuAction())

        self.retranslateUi(MainWindow)
        self.stacked_widget.setCurrentIndex(0)
        self.bouquets_action.toggled['bool'].connect(self.bouquet_tool_button.setVisible)
        self.satellites_action.toggled['bool'].connect(self.satellite_tool_button.setVisible)
        self.picons_action.toggled['bool'].connect(self.picon_tool_button.setVisible)
        self.tv_action.toggled['bool'].connect(self.tv_tool_button.setVisible)
        self.epg_action.toggled['bool'].connect(self.epg_tool_button.setVisible)
        self.timer_action.toggled['bool'].connect(self.timer_tool_button.setVisible)
        self.ftp_action.toggled['bool'].connect(self.ftp_tool_button.setVisible)
        self.logo_action.toggled['bool'].connect(self.logo_tool_button.setVisible)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "E2Toolkit"))
        self.profile_combo_box.setToolTip(_translate("MainWindow", "Profile"))
        self.download_tool_button.setToolTip(_translate("MainWindow", "Receive files from the receiver"))
        self.download_tool_button.setText(_translate("MainWindow", "Receive"))
        self.upload_tool_button.setToolTip(_translate("MainWindow", "Send files to the receiver"))
        self.upload_tool_button.setText(_translate("MainWindow", "Send"))
        self.bouquet_tool_button.setText(_translate("MainWindow", "Bouquets"))
        self.satellite_tool_button.setText(_translate("MainWindow", "Satellites"))
        self.picon_tool_button.setText(_translate("MainWindow", "Picons"))
        self.tv_tool_button.setText(_translate("MainWindow", "TV"))
        self.epg_tool_button.setText(_translate("MainWindow", "EPG"))
        self.timer_tool_button.setText(_translate("MainWindow", "Timer"))
        self.ftp_tool_button.setText(_translate("MainWindow", "FTP"))
        self.logo_tool_button.setText(_translate("MainWindow", "Logo"))
        self.control_tool_button.setText(_translate("MainWindow", "Control"))
        self.services_group_box.setTitle(_translate("MainWindow", "Services"))
        self.filter_free_button.setText(_translate("MainWindow", " Free"))
        self.service_filter_edit.setToolTip(_translate("MainWindow", "Filter"))
        self.service_search_edit.setToolTip(_translate("MainWindow", "Search text"))
        self.service_search_edit.setPlaceholderText(_translate("MainWindow", "Search..."))
        self.tv_label.setText(_translate("MainWindow", "TV:"))
        self.tv_count_label.setText(_translate("MainWindow", "0"))
        self.radio_label.setText(_translate("MainWindow", "Radio:"))
        self.radio_count_label.setText(_translate("MainWindow", "0"))
        self.data_label.setText(_translate("MainWindow", "Data:"))
        self.data_count_label.setText(_translate("MainWindow", "0"))
        self.fav_group_box.setTitle(_translate("MainWindow", "Bouquet services"))
        self.fav_menu_button.setToolTip(_translate("MainWindow", "Tools"))
        self.fav_menu_button.setText(_translate("MainWindow", "Tools"))
        self.bq_service_search_edit.setPlaceholderText(_translate("MainWindow", "Search..."))
        self.bouquets_group_box.setTitle(_translate("MainWindow", "Bouquets"))
        self.add_bouquet_button.setToolTip(_translate("MainWindow", "Add"))
        self.add_bouquet_button.setText(_translate("MainWindow", "Add"))
        self.file_menu.setTitle(_translate("MainWindow", "File"))
        self.help_menu.setTitle(_translate("MainWindow", "Help"))
        self.settings_menu.setTitle(_translate("MainWindow", "Settings"))
        self.language_menu.setTitle(_translate("MainWindow", "Language"))
        self.view_menu.setTitle(_translate("MainWindow", "View"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.open_action.setText(_translate("MainWindow", "Open"))
        self.open_action.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.exit_action.setText(_translate("MainWindow", "Exit"))
        self.exit_action.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.settings_action.setText(_translate("MainWindow", "Settings..."))
        self.menu_action_search.setText(_translate("MainWindow", "Search"))
        self.menu_action_search.setShortcut(_translate("MainWindow", "Ctrl+F"))
        self.menu_action_filter.setText(_translate("MainWindow", "Filter"))
        self.menu_action_filter.setShortcut(_translate("MainWindow", "Ctrl+Shift+F"))
        self.import_action.setText(_translate("MainWindow", "Import"))
        self.extract_action.setText(_translate("MainWindow", "Extract..."))
        self.about_action.setText(_translate("MainWindow", "About"))
        self.english_lang_action.setText(_translate("MainWindow", "English"))
        self.bouquets_action.setText(_translate("MainWindow", "Bouquets"))
        self.satellites_action.setText(_translate("MainWindow", "Satellites"))
        self.picons_action.setText(_translate("MainWindow", "Picons"))
        self.tv_action.setText(_translate("MainWindow", "TV"))
        self.epg_action.setText(_translate("MainWindow", "EPG"))
        self.timer_action.setText(_translate("MainWindow", "Timer"))
        self.ftp_action.setText(_translate("MainWindow", "FTP"))
        self.logo_action.setText(_translate("MainWindow", "Logo"))
